import "./globals.css";
import { Inter } from "next/font/google";
import RunningText from "@/components/Runing-text";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="hidden md:block lg:hidden">
          Visible on medium screens
        </div>
        <div className="md:hidden lg:block">
          Visible on small and large screens
        </div>
        <RunningText
          text="THÔNG BÁO : Trong toán học và nghệ thuật, hai đại lượng được gọi là có tỷ số vàng hay tỷ lệ vàng nếu tỷ số giữa tổng của các đại lượng đó với đại lượng lớn hơn bằng tỷ số giữa đại lượng lớn hơn với đại lượng nhỏ hơn."
        />
        <div className="w-full whitespace-nowrap overflow-hidden text-overflow-ellipsis"></div>
        {children}
      </body>
    </html>
  );
}
