import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./components/Footer/Footer";
import HeaderSideBar from "./components/HeaderSideBar/HeaderSideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Apple ID",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-[98vh]">
          <HeaderSideBar children={children} />
        </div>
        <Footer />
      </body>
    </html>
  );
}
