import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import HeaderSideBar from "./components/HeaderSideBar";
import Provider from "./components/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Apple ID",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Provider>
          <div className="flex min-h-[98vh]">
            <HeaderSideBar children={children} />
          </div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
